treaville/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from treaville.config import Config


mail = Mail()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'clients.login'
bcrypt = Bcrypt()
admin = Admin()





def create_app(config_class = Config):
    app = Flask(__name__) 
    app.config.from_object(Config)
    mail.init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)
    admin.init_app(app)
    login_manager.init_app(app)
    
    from treaville.client.routes import clients
    from treaville.main.routes import main
    from treaville.transpoter.routes import transpot
    from treaville.vehicle.route import vehicless
    from treaville.book.route import book
    from treaville.admin import adm

    app.register_blueprint(book)
    app.register_blueprint(clients)
    app.register_blueprint(main)
    app.register_blueprint(transpot)
    app.register_blueprint(vehicless)
    app.register_blueprint(adm)

    with app.app_context():
        db.create_all()

    return app

treaville/admin/__init__.py
from flask import Blueprint, abort, session
from treaville.model import Bookingcargo
from treaville.model import Transporter, Vehicle, Client
from treaville import db, admin, create_app
from flask_admin.contrib.sqla import ModelView
from flask import  url_for, redirect, request
from flask_security import Security, SQLAlchemyUserDatastore, login_required, current_user
from flask_security.utils import encrypt_password
from flask_admin.contrib import sqla
from flask_admin import BaseView, expose


adm = Blueprint("adm", __name__)
        
    
admin.name = "Admin Panel"

class SecuredModel(ModelView):
    def is_accessible(self):
        if "logged_in" in session:
            return True
        else:
            abort(403)
    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('clients.login', next=request.url))
    
class SecureModel(ModelView):
    def is_accessible(self):
        if "logged_in" in session:
            return True
        else:
            abort(403)
    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('clients.login', next=request.url))
    column_searchable_list = ['alt_mobile']
    column_filters = ['alt_mobile']

class AnalyticsView(BaseView):
    @expose('/')
    def index(self):
        vehicles= Vehicle.query.all()
        return self.render('transpotervehicle.html',  vehicles = vehicles)

admin.add_view(AnalyticsView(name='VERIFY VEHICLE', endpoint='analytics'))


admin.add_view(SecuredModel(Bookingcargo, db.session))
admin.add_view(SecureModel(Transporter, db.session))
admin.add_view(SecuredModel(Vehicle, db.session))
admin.add_view(SecuredModel(Client, db.session))

treaville/client/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request, session
from treaville import db, bcrypt
import flask_bcrypt
from flask_login import login_user, logout_user
from treaville.model import Client,Transporter
from treaville.client.form import Clientform, Login
from treaville.transpoter.form import Transporterform


clients = Blueprint('clients', __name__)

@clients.route("/clientsignup", methods=['GET','POST'])
def clientsignup():
    Lform = Login()
    Cform = Clientform()
    if Cform.validate_on_submit():
        hashed_passwed = flask_bcrypt.generate_password_hash(Cform.password.data).decode('utf-8')
        client = Client(full_name = Cform.full_name.data, company_name = Cform.company_name.data, id_number = Cform.id_number.data,email = Cform.email.data,
                        aop = Cform.aop.data, city = Cform.city.data, password = hashed_passwed,mobile_number = Cform.mobile_number.data, 
                        alt_mobile_number = Cform.alt_mobile_number.data)
        db.session.add(client)
        db.session.commit()
        return redirect(url_for('clients.clientsignup'))
    return render_template('clientsignup.html', Cform = Cform, Lform = Lform)

@clients.route("/login", methods=['POST', 'GET'])
def login():
    Tform = Transporterform()
    Lform = Login()
    if Lform.validate_on_submit():
        transporter = Transporter.query.filter_by(email_adress = Lform.email.data).first()
        client = Client.query.filter_by(email = Lform.email.data).first()
        if transporter and bcrypt.check_password_hash(transporter.login_password, Lform.password.data):
            session['user_type'] = 'transporter'
            if transporter.pending:
                return render_template('test.html')
            login_user(transporter)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('transpot.dashboard'))
        if client and bcrypt.check_password_hash(client.password, Lform.password.data):
            session['user_type'] = 'client'
            login_user(client)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('book.booking'))
        if Lform.email.data == "admin@gmail.com" and Lform.password.data == "Admin":
            session['logged_in'] = True
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect("/admin")
        else:
            return redirect(url_for('clients.clientsignup'))
    return render_template('transportersignup.html', Lform = Lform, form = Tform)


@clients.route('/logout')
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('main.home'))

treaville/main/routes.py
from flask import Blueprint
from flask import render_template


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('index.html')

@main.route('/aboutus')
def aboutus():
    return render_template("aboutus.html")

treaville/transpoter/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, request, session, send_file
from treaville import db, bcrypt, mail
import flask_bcrypt
from flask_mail import Message
from flask_login import login_user, login_required, current_user, logout_user
from treaville.model import Client,Transporter, Vehicle, Bookingcargo, Bookingconstraction,Bookingpassenger
from treaville.transpoter.form import Transporterform, Login
from treaville.vehicle.form import  Vehicleform
from io import BytesIO


transpot = Blueprint('transpot', __name__)

@transpot.route('/transpoter')
def transpoter():
    return render_template("transporter.html")

@transpot.route('/signup', methods=['GET','POST'])
def transportersignup():
    Lform = Login()
    Tform = Transporterform()
    if Tform.validate_on_submit():
        hashed_passwed = flask_bcrypt.generate_password_hash(Tform.login_password.data).decode('utf-8')
        transpoter = Transporter(full_name = Tform.full_name.data, 
                                 company_name = Tform.company_name.data,
                                   Id_number = Tform.Id_number.data, 
                                   email_adress = Tform.email_adress.data,
                                     login_password = hashed_passwed, 
                                     owner_mobile = Tform.owner_mobile.data,
                                       alt_mobile = Tform.alt_mobile.data)
        db.session.add(transpoter)
        db.session.commit()
        return redirect(url_for('transpot.transportersignup'))
    return render_template("transportersignup.html", form = Tform, Lform = Lform)


@transpot.route("/login", methods=['POST', 'GET'])
def login():
    Tform = Transporterform()
    Lform = Login()
    if Lform.validate_on_submit():
        transporter = Transporter.query.filter_by(email_adress = Lform.email.data).first()
        client = Client.query.filter_by(email = Lform.email.data).first()
        if transporter and bcrypt.check_password_hash(transporter.login_password, Lform.password.data):
            session['user_type'] = 'transporter'
            login_user(transporter)
            if transporter.pending:
                return render_template('test.html')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('transporter.dashboard'))
        if client and bcrypt.check_password_hash(client.password, Lform.password.data):
            session['user_type'] = 'client'
            login_user(client)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('book.booking'))
        else:
            return redirect(url_for('clients.clientsignup'))
    return render_template('transportersignup.html', Lform = Lform, form = Tform)

@transpot.route('/aprroved/<int:id>', methods = ['POST', 'GET'])
def approve_vehicle(id):
    vehicle = Vehicle.query.filter_by(id = id).first()
    vehicle.approved = True
    db.session.commit()
    return redirect('/admin/analytics/')


@transpot.route('/dashboard', methods = ['POST', 'GET'])
@login_required
def dashboard():
    Vform = Vehicleform()
    jobcargo = []
    jobpassenger = []
    jobconstruction = []
    vehicles = Vehicle.query.filter_by(owner = current_user.id).all()
    me = Transporter.query.filter_by(id = current_user.id).first()
    for jobc in Bookingcargo.query.all():
        if jobc in me.requestscargo:
            pass
        else:
            jobcargo.append(jobc)
    for jobp in Bookingpassenger.query.all():
        if jobp in me.requestspassenger:
            pass
        else:
            jobpassenger.append(jobp)
    for jobco in Bookingconstraction.query.all():
        if jobco in me.requestsConstraction:
            pass
        else:
            jobconstruction.append(jobco)
            
    if Vform.validate_on_submit():
        file1 = request.files['license']
        data = file1.read()
        file2 = request.files['logbook']
        data1 = file2.read()
        vehicle = Vehicle(vehicle_type = Vform.vehicle_type.data, driver_name = Vform.driver_name.data,driver_id = Vform.driver_id.data, driver_no = Vform.drivers_no.data,
                          alt_no = Vform.alt_no.data, payment_account = Vform.pay_account.data, account_name =Vform.account_name.data, band_branch_name = Vform.branch_name.data,
                          aop = Vform.aop.data, town = Vform.town.data, log_book = data1, log_book_name = file2.filename, licence = data, licence_name =file1.filename  ,owner = current_user.id)
        db.session.add(vehicle)
        db.session.commit()
        current_user.vehicle.append(vehicle)
        db.session.commit()
        return redirect(url_for('transpot.dashboard'))
    return render_template("dashboard.html", Vform = Vform, jobcargo = jobcargo, jobpassenger = jobpassenger, jobconstruction = jobconstruction, vehicles = vehicles)




@transpot.route("/request/<my_id>", methods=['GET'])
@login_required
def requesta(my_id):
    transpoter = Transporter.query.filter_by(id = current_user.id).first()
    requests = Bookingcargo.query.filter_by(my_id = my_id).first()
    requestP = Bookingpassenger.query.filter_by(my_id = my_id).first()
    requestC = Bookingconstraction.query.filter_by(my_id = my_id).first()
    print(requests)
    if requests:
        msg_title = "A transporter is requesting to handle a service"
        sender = "noreply@app.com"
        msg = Message(msg_title, sender=sender, recipients=['harmonymwirigi99@gmail.com'])
        data = {
            'app_name': 'TREAVILLE EDGE',
            'title' : msg_title,
            'name': transpoter.full_name,
            'service_id': requests.my_id,
            'email': transpoter.email_adress,
            'phone_numer': transpoter.owner_mobile,
            'company': requests.company,
            'my_id': requests.my_id,
            'cargo_type': requests.cargo_type,
            'width' : requests.cargo_wight,
            'volume': requests.cargo_volume,
            'vehicle': requests.vehicle_type,
            'pickup':requests.pickup_location,
            'destination': requests.delivery_destination,
            'offer_amount': requests.offer_amount,
            'time': requests.date_made.strftime('%Y%m%d'),
        }
        msg.html = render_template("transporterrequest.html", data = data)
        try:
            if mail.send(msg):
                transpoter.requestscargo.append(requests)
                db.session.commit()
                return redirect(url_for('transpot.dashboard'))
        except Exception as e:
            print(e)
            return "the email was not sent{e}"
    if requestP:
        transpoter.requestspassenger.append(requestP)
        db.session.commit()
        msg_title = "Congratulations, Someone just booked a service"
        sender = "noreply@app.com"
        msg = Message(msg_title, sender=sender, recipients=['harmonymwirigi99@gmail.com'])
        msg_body = "Client information"
        data = {
            'app_name': 'TREAVILLE EDGE',
            'title' : msg_title,
            'body' : msg_body,
            
        }
        msg.html = render_template("bookingemail.html", data = data)
        try:
            mail.send(msg)
            return "email sent"
        except Exception as e:
            print(e)
            return "the email was not sent{e}"
    if requestC:
        transpoter.requestsConstraction.append(requestC)
        db.session.commit()
        msg_title = "Congratulations, Someone just booked a service"
        sender = "noreply@app.com"
        msg = Message(msg_title, sender=sender, recipients=['harmonymwirigi99@gmail.com'])
        msg_body = "Client information"
        data = {
            'app_name': 'TREAVILLE EDGE',
            'title' : msg_title,
            'body' : msg_body,
        }
        msg.html = render_template("bookingemail.html", data = data)
        try:
            mail.send(msg)
            return "email sent"
        except Exception as e:
            print(e)
            return "the email was not sent{e}"
    
    return redirect(url_for('transpot.dashboard'))

@transpot.route("/download/<id>")
@login_required
def download(id):
    licence = Vehicle.query.filter_by(id=id).first()
    return send_file(BytesIO(licence.log_book), download_name=licence.licence_name, as_attachment=True)

@transpot.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

treaville/templates/aboutus.html
<!DOCTYPE html>
<html lang="en">


<!--trevysedge-->

  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Trevysedge</title>
  <meta content="" name="description">
  <meta content="" name="keywords">


  <link href="/static/assets/img/favicon.png" rel="icon">
  <link href="/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <link href="/static/assets/css/style.css" rel="stylesheet">

</head>



    <!-- ======= About Section ======= -->
       <div class="d-flex open-page-header">
        <div class="container">
         <a href="index.html" class="logo"><img src="/static/assets/img/logonoBG.png" alt="" class="img-fluid"></a>
            <h1> Our Story </h1>

        </div>
      </div>
    <section id="about" class="about">
 

      <div class="container">
      
        <div class="row">
        
          <div class="col-lg-6 pt-4 pt-lg-0 content">
            <h3>About Trevy's Edge</h3>
            <p class="fst">
              Treaville Edge Trucks has been in operation since 2015 and is the fastest growing transport company in
Kenya. We aim to provide our clients with the most affordable rates for transporting goods within the
country and across the neighbouring countries. Our network, field operations and planning will be able to
offer our clients upto 40% discounts to most destinations. The client sets the price and our transporters
proceed to bid for the jobs.
            </p>
          
            <p>
            We offer solutions related to Transport, Passenger & Tour Vehicles and Construction Vehicles. We will be
able to offer great discounts for services in these 3 transport categories that will be beneficial to clients and
service providers.
            </p>
          </div>
            <div class="col-lg-6">
            <img src="/static/assets/img/illustrations/crafty-red-truck-transports-boxes-of-stuff-to-a-certain-point-1.png" class="img-fluid" alt="">
          </div>
        </div>

      </div>
    </section><!-- End About Section -->
    
        <section id="about2" class="about">
 

      <div class="container">
      
        <div class="row">
          <div class="col-lg-6">
            <img src="/static/assets/img/illustrations/revtruck.png" class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content">
          
      
            <p class="fst">
              We will connect you to our transport professionals who will provide services with utmost courtesy.
Treaville Edge makes it fast, simple and cost-effective to find the best transporters in the industry offering
best discounted prices from various destinations in the country.

            </p>
          
            <p>
        We pride ourselves in being an innovative transport company that connects customers in need of
affordable transport to bidders willing to provide services at negotiated prices. Transporters in turn
benefit by getting guaranteed cargo on all their trips to various destinations. 

            </p>
          </div>
          
        </div>

      </div>
    </section><!-- End About Section -->
<div class="core-values-container">
		<h2>Our Core Values</h2>
<div id="services">
<div class="content-box-md">
<div class="container">
<div class="row">
  <div class="col-md-4">
   <div class="service">
   <h5>Affordable Solution:</h5>
   <hr>
   <li>Our team works tirelessly to develop innovative transport solutions that are most affordable for our clients. This is the most important pillar
that we promise to deliver to our clients.
</li>
  
   </div>
  </div>

  <div class="col-md-4">
      <div class="service">
      <h5>Service Oriented:</h5>
      <hr>
      <li>Our team will be attentive to your needs and will do everything possible to get a solution to any issue that occurs during provision of service
to our clients. They will be at hand to advise customers accordingly.</li>
      
      </div>
  </div>

    <div class="col-md-4">
        <div class="service">
        <h5>Integrity:</h5>
        <hr>
        <li>We endeavour to do our work and deliver exceptional service to our clients with integrity and transparency.
</li>
   
        </div>
    </div>

  <div class="col-md-4">
   <div class="service">
   <h5>Professionalism:</h5>
   <hr>
   <li>We have hired qualified professionals who are well trained to handle business transactions professionally and to provide you with
exceptional services.
</li>

   </div>
  </div>

   <div class="col-md-4">
   <div class="service">
   <h5>Reliability:</h5>
   <hr>
   <li>Our team strives hard to ensure that your job is done well and meets your expectation in an efficient, secure manner and timely manner.
</li>

   </div>
  </div>


</div>
</div>
</div>
</div>


		
	</div>
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact" id="footer-logo">
        <a href="home.html" class="logo"><img src="/static/assets/img/logonoBG.png" alt="" class="img-fluid"></a>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="login.html">SignUp</a></li>
                 <li><i class="bx bx-chevron-right"></i> <a href="#">Rate Calculator</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Help and FAQs</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Partner with us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="privacypolicy.html">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
             <li><i class="bx bx-chevron-right"></i> <a href="404.html">Cargo transportation</a></li>           
              <li><i class="bx bx-chevron-right"></i> <a href="404.html">Courier and logistics</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="404.html">Office Relocation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">House moving</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Tour vans and buses</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Construction vehicles</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Subscribe to our newsletter to receive updates from us. Subscription is free, no advertisements.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Trevy's Edge</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
        By <a href="https://cpyder.net/">:  CpyderWeb</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

    
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/assets/vendor/php-email-form/validate.js"></script>
  <script src="/static/assets/vendor/purecounter/purecounter.js"></script>
  <script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/js/main.js"></script>

</body>



</html>

treaville/templates/bookingemail.html
<!DOCTYPE html>
<html>
<head>
  <title>Email Template</title>
   <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{{data.title}}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">


  <link href="/static/assets/img/favicon.png" rel="icon">
  <link href="/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">

  <link href="/static/assets/css/emailstyle.css" rel="stylesheet">
</head>
<body>
  <table cellpadding="0" cellspacing="0" border="0" width="100%">
    <tr>
      <td align="center" class="banner" >
        <table cellpadding="0" cellspacing="0" border="0" width="600">
          <tr>
            <td align="center" valign="top" style="padding: 20px;">
              <img src="/static/assets/img/logonoBG.png" alt="Logo" width="200" style="display: block; max-width: 100%;">
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#f9f9f9">
        <table cellpadding="0" cellspacing="0" border="0" width="600">
          <tr>
            <td valign="top" style="padding: 20px;">
              
<div class="container">
    <div class="header">

    <h2>{{data.title}}</h2>

        <h5>{{data.body}}</h5>
             <strong>Name:</strong> {{data.name}}<br>
             <strong>Email:</strong>{{data.email}} <br>
             <strong>Phone Number:</strong> {{data.phone_numer}} <br>
             <strong>Company Name:</strong> {{data.service_id }} <br>

<hr>

           <h5>Service details</h5>
                <strong>Service ID:</strong>{{data.my_id}} <br>
                <strong>Service:</strong> Cargo Transportation<br>
                <strong>Cargo Type:</strong>{{data.cargo_type}} <br>  
                <strong>Height:</strong> N/A<br>
                <strong>Width:</strong>{{data.width}} <br>
                <strong>Length:</strong> N/A<br>
                <strong>Volume:</strong>{{data.volume}} <br>
                <strong>No.Of Passengers</strong> N/A<br>
                <strong>Vehicle:</strong>{{data.vehicle}} <br>
                <strong>Pickup Location:</strong>{{data.pickup}} <br>
                <strong>Destination:</strong>{{data.destination}} <br>
                <strong>Construction Site:</strong>N/A <br>
                <strong>Offer amount:</strong> {{data.offer_amount}} <br>
                <strong>Time:</strong>{{data.time}} <br>

    </div>

    <div class="body">
     
    
    </div>

 

    <div class="actions">
         <a class="reply-button" href="mailto:example@example.com">Reply</a>
            
    </div>
  </div>




          
              
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td align="center" bgcolor="#f1f1f1">
        <table cellpadding="0" cellspacing="0" border="0" width="600">
          <tr>
            <td valign="top" style="padding: 20px;">
              <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>
                  <td width="50%" style="padding-right: 10px;">
                    <img src="/static/assets/img/logonoBG.png" alt="Footer Logo" width="100" style="display: block; max-width: 100%;">
                  </td>
                  <td width="50%" style="padding-left: 10px;">
                    <p> </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>

treaville/templates/test.html
<html>
    <head>

    </head>
    <body>
        <p>Test pass</p>
    </body>
</html>

treaville/templates/transpotervehicle.html
{% extends 'admin/master.html' %}
{% block body %}
{% if vehicles %}
        <table style="margin: 3rem;width: 100%;">
                <tr style="padding: 3rem;">
                        <th>DRIVERS NAME </th>
                        <th>DRIVERS ID</th>
                        <th>DRIVER NUMBER </th>
                        <th>DRIVER LICENCE</th>
                        <th>TRANSPOTER</th>
                        <th>APPROVE</th>

                </tr>
                {% for vehicle in vehicles %}
                <tr style="align-items: center;text-align: center;">
                        <td>{{vehicle.driver_name}}</td>
                        <td>{{vehicle.driver_id}}</td>  
                        <td>{{vehicle.driver_no}}</td>  
                        <td><a href="{{url_for('transpot.download', id = vehicle.id)}}">{{vehicle.licence_name}}</a></td>
                        <td> {{vehicle.OWNEDBY}}</td>
                        {% if vehicle.approved %} 
                        <td>APPROVED</td>
                        {% else %}
                                <form action="{{url_for('transpot.approve_vehicle', id = vehicle.id)}}" method="post"> 
                                        <td><input type="checkbox"> </td> 
                                        <td><input type="submit" name="SAVE"></td> 
                                </form>
                        {% endif %}

                </tr>
                {% endfor %}
        </table>
        {% endif %}
{% endblock %}